// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: query.sql

package querytest

import (
	"context"
)

const listAuthors = `-- name: ListAuthors :one
SELECT  id, bio
FROM    authors
WHERE   id = ?
        OR bio = ?
LIMIT   1
`

func (q *Queries) ListAuthors(ctx context.Context, myNamedParam int64) (Author, error) {
	row := q.db.QueryRowContext(ctx, listAuthors, myNamedParam)
	var i Author
	err := row.Scan(&i.ID, &i.Bio)
	return i, err
}
