// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: query.sql

package querytest

import (
	"context"
)

const deleteBarByID = `-- name: DeleteBarByID :execrows
DELETE FROM bar WHERE id = $1
`

func (q *Queries) DeleteBarByID(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBarByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBarByIDAndName = `-- name: DeleteBarByIDAndName :execrows
DELETE FROM bar WHERE id = $1 AND name = $2
`

type DeleteBarByIDAndNameParams struct {
	ID   int32
	Name string
}

func (q *Queries) DeleteBarByIDAndName(ctx context.Context, arg DeleteBarByIDAndNameParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBarByIDAndName, arg.ID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
